<a href="https://colab.research.google.com/github/Praveenku32k/Natural_Language_Processing/blob/main/tensor_with_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

# Abs

In [2]:
x = tf.constant([-2.25, 3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [3]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.2>

# Complex

In [4]:
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [5]:
tf.sqrt(-2.25**2+4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=4.1833>

In [6]:
x_1=tf.constant([5,3,4,6,9],dtype=tf.int32)
x_2=tf.constant([7,6,2,7,6],dtype=tf.int32)

In [7]:
print(tf.add(x_1,x_2))

tf.Tensor([12  9  6 13 15], shape=(5,), dtype=int32)


In [8]:
print(tf.multiply(x_1,x_2))

tf.Tensor([35 18  8 42 54], shape=(5,), dtype=int32)


In [9]:
print(tf.divide(x_1,x_2))

tf.Tensor([0.71428571 0.5        2.         0.85714286 1.5       ], shape=(5,), dtype=float64)


In [11]:
x_1=tf.constant([5,3,4,6,9],dtype=tf.float32)
x_2=tf.constant([7],dtype=tf.float32)

In [12]:
print(tf.math.add(x_1,x_2))

tf.Tensor([12. 10. 11. 13. 16.], shape=(5,), dtype=float32)


In [14]:
x_1=tf.constant([5,3,4,6,9],dtype=tf.float32)
x_2=tf.constant([[7],[5],[7]],dtype=tf.float32)
print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1,x_2))

(5,)
(3, 1)
tf.Tensor(
[[35. 21. 28. 42. 63.]
 [25. 15. 20. 30. 45.]
 [35. 21. 28. 42. 63.]], shape=(3, 5), dtype=float32)


# Maximum tf.math

In [15]:
A = tf.constant([2, 20, 30, 3, 6])

In [16]:
print(tf.math.argmax(A)) # it will return the  index position .

tf.Tensor(2, shape=(), dtype=int64)


In [17]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])

In [19]:
print(tf.math.argmax(B,1)) # column wise maximun index

tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [20]:
print(tf.math.argmax(B,0))# compression is done with columns wise.

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [22]:
print(B.shape)

(3, 5)


In [23]:
print(tf.math.argmin(B,1))

tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [26]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x, y)  # [[8, 0], [3, 81]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [28]:
tf.pow(tf.constant(2),tf.constant(6))

<tf.Tensor: shape=(), dtype=int32, numpy=64>

# reduce_sum

In [29]:
x = tf.constant([[1, 1, 1], [1, 1, 1]])
x.numpy()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [30]:
tf.reduce_sum(x).numpy()

6